



s = "CAAGCACACATTCCCAATGAGTGTTTTCGCTAATTCTCAAACGGATTCATTATTTTCGCGGATAGATTGTTCCCATCCCAGTTGTTAGAGATCTGTACCCTACACTTCTGAAAACAAGAGACAAACTGGATTTCGCCTGACAATACTCAGGCGTCTTCGCGTTGAACCCATAGGGGTCTCAATGTGGGGGGAGGATATAATATACACCAAGGGCGGCGGGGCGGAGTTCCGGGCCGGTTCTAACGATCGGCGATCGACCTCAATAAACTTAAATATGCAGACTCCAATTAAACCTTCGTAACTGTCTTAGCGCAGGTCATTGGTTAGCGTCACGTTCTGGCTGGAGATACGAGTTTCCAGTAACATGCATCGGCCTAGGCTAGTCCTTAGCAACTATTGGGTCCCGCCAGGTAGCACAGCAATGCTAGCGATCTGCCTGACCGGACTATTCCACTTAAGGTGGAAAACTGTCTGCCGCTACGTTTTTGGCCTTGACTATGCGAGCATTAATTAACAAAAGGTGGGAGGACTTTCACTTGCCTCTGTACATTAAGGCTCTGAGCGACCTCGAGGGGGATGGGTAGCAAGATCCCCGGGATTACTCTGAAAGGTGCCTTTGTGCGGTCCCAACCTAGTGATAGTGAAATCTCGCAAGAACCCACACTCGTGTACCCGCTAGAGGCCTGAGGACGTGCCCACAAGCTAGAACCTTGCTTTTCTTTGAAAGCTTTAAGGGTGTTTGACCAACTACCTTGCCTTCGTGGCTGTTTTACAGGCAGGCACCGGGCATATTCTTGGGACTAAACGTGTAGAGTGGCGGTTACGAGCCCGGGCAACATGGCGGAAGTACCCAAGCTTGAATGTGAGAGAAATGCTCGTGAGTTATAAAGTCACTTACACTCGCTGGCAAGTATCGAGACCG"
c = ""
for i in s:
    if i =='A':
        c = c+'T'
    elif i =='T':
        c +='A'
    elif i =='C':
        c +='G'
    elif i =='G':
        c +='C'
print c[::-1]


